In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [3]:
df = pd.read_csv('twitter_training.csv')

In [4]:
df.head()

2401  Borderlands  Positive  \
0  2401  Borderlands  Positive   
1  2401  Borderlands  Positive   
2  2401  Borderlands  Positive   
3  2401  Borderlands  Positive   
4  2401  Borderlands  Positive   

  im getting on borderlands and i will murder you all ,  
0  I am coming to the borders and I will kill you...     
1  im getting on borderlands and i will kill you ...     
2  im coming on borderlands and i will murder you...     
3  im getting on borderlands 2 and i will murder ...     
4  im getting into borderlands and i can murder y...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74681 entries, 0 to 74680
Data columns (total 4 columns):
 #   Column                                                 Non-Null Count  Dtype 
---  ------                                                 --------------  ----- 
 0   2401                                                   74681 non-null  int64 
 1   Borderlands                                            74681 non-null  object
 2   Positive                                               74681 non-null  object
 3   im getting on borderlands and i will murder you all ,  73995 non-null  object
dtypes: int64(1), object(3)
memory usage: 2.3+ MB


In [6]:
df['Tag'] = df['Borderlands']
df['sentiment'] = df['Positive']
df['text'] = df['im getting on borderlands and i will murder you all ,']
df = df.drop(['2401','Borderlands','Positive','im getting on borderlands and i will murder you all ,','Tag'],axis=1)
df.head()

sentiment                                               text
0  Positive  I am coming to the borders and I will kill you...
1  Positive  im getting on borderlands and i will kill you ...
2  Positive  im coming on borderlands and i will murder you...
3  Positive  im getting on borderlands 2 and i will murder ...
4  Positive  im getting into borderlands and i can murder y...

In [7]:
pd.get_dummies(df['sentiment'],drop_first=True)

Negative  Neutral  Positive
0             0        0         1
1             0        0         1
2             0        0         1
3             0        0         1
4             0        0         1
...         ...      ...       ...
74676         0        0         1
74677         0        0         1
74678         0        0         1
74679         0        0         1
74680         0        0         1

[74681 rows x 3 columns]

In [8]:
df

sentiment                                               text
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[74681 rows x 2 columns]

In [9]:
df = df.drop(df[df['sentiment']=='Neutral'].index,axis=0)

In [10]:
df

sentiment                                               text
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[56363 rows x 2 columns]

In [11]:
df = df.drop(df[df['sentiment']=='Irrelevant'].index,axis=0)

In [12]:
df

sentiment                                               text
0      Positive  I am coming to the borders and I will kill you...
1      Positive  im getting on borderlands and i will kill you ...
2      Positive  im coming on borderlands and i will murder you...
3      Positive  im getting on borderlands 2 and i will murder ...
4      Positive  im getting into borderlands and i can murder y...
...         ...                                                ...
74676  Positive  Just realized that the Windows partition of my...
74677  Positive  Just realized that my Mac window partition is ...
74678  Positive  Just realized the windows partition of my Mac ...
74679  Positive  Just realized between the windows partition of...
74680  Positive  Just like the windows partition of my Mac is l...

[43373 rows x 2 columns]

In [13]:
df = pd.get_dummies(df,columns=['sentiment'],drop_first=True)
df

text  sentiment_Positive
0      I am coming to the borders and I will kill you...                   1
1      im getting on borderlands and i will kill you ...                   1
2      im coming on borderlands and i will murder you...                   1
3      im getting on borderlands 2 and i will murder ...                   1
4      im getting into borderlands and i can murder y...                   1
...                                                  ...                 ...
74676  Just realized that the Windows partition of my...                   1
74677  Just realized that my Mac window partition is ...                   1
74678  Just realized the windows partition of my Mac ...                   1
74679  Just realized between the windows partition of...                   1
74680  Just like the windows partition of my Mac is l...                   1

[43373 rows x 2 columns]

In [14]:
df

text  sentiment_Positive
0      I am coming to the borders and I will kill you...                   1
1      im getting on borderlands and i will kill you ...                   1
2      im coming on borderlands and i will murder you...                   1
3      im getting on borderlands 2 and i will murder ...                   1
4      im getting into borderlands and i can murder y...                   1
...                                                  ...                 ...
74676  Just realized that the Windows partition of my...                   1
74677  Just realized that my Mac window partition is ...                   1
74678  Just realized the windows partition of my Mac ...                   1
74679  Just realized between the windows partition of...                   1
74680  Just like the windows partition of my Mac is l...                   1

[43373 rows x 2 columns]

In [15]:
d = df.dropna()
df

text  sentiment_Positive
0      I am coming to the borders and I will kill you...                   1
1      im getting on borderlands and i will kill you ...                   1
2      im coming on borderlands and i will murder you...                   1
3      im getting on borderlands 2 and i will murder ...                   1
4      im getting into borderlands and i can murder y...                   1
...                                                  ...                 ...
74676  Just realized that the Windows partition of my...                   1
74677  Just realized that my Mac window partition is ...                   1
74678  Just realized the windows partition of my Mac ...                   1
74679  Just realized between the windows partition of...                   1
74680  Just like the windows partition of my Mac is l...                   1

[43373 rows x 2 columns]

In [16]:
x = d.drop('sentiment_Positive',axis=1)
y = d['sentiment_Positive']
xtrain,xtest,ytran,ytest = train_test_split(x,y,test_size=0.3,random_state=101)

In [23]:
cv = CountVectorizer()
s_xtrain = cv.fit_transform(xtrain['text'])
s_xtrain
s_xtext = cv.transform(xtest['text'])

### Using Multinomial NB

In [19]:
nb = MultinomialNB()
nb.fit(s_xtrain,ytran)
ypred = nb.predict(s_xtext)


In [20]:
ypred

array([1, 1, 0, ..., 0, 1, 0], dtype=uint8)

In [21]:
ytest

29064    1
27807    1
13800    0
47507    1
70463    0
        ..
42862    0
48571    0
67886    0
47682    0
33435    0
Name: sentiment_Positive, Length: 12904, dtype: uint8

Accuracy in **Multinomial NB**

In [22]:
accuracy_score(ytest,ypred)

0.8817420954742715

### Using Gaussian NB

In [26]:
gnb = GaussianNB()
gnb.fit(s_xtrain.toarray(),ytran)
ypred = gnb.predict(s_xtext.toarray())
ypred

array([1, 1, 1, ..., 0, 0, 0], dtype=uint8)

Accuracy in **Gaussian NB**

In [27]:
accuracy_score(ytest,ypred)

0.7985120892746436

Using Bernoulli NB

In [30]:
bnb = BernoulliNB()
bnb.fit(s_xtrain,ytran)
ypred = bnb.predict(s_xtext)
ypred

array([1, 1, 1, ..., 0, 1, 0], dtype=uint8)

Accuracy in **Bernoulli NB**

In [29]:
accuracy_score(ytest,ypred)

0.8413670179789212